### ISSUE TITLE
ValueError: An upper bound is less than the corresponding lower bound.

### ISSUE THREAD

**Issue by sgofferj** [knipknap/better-tool-library#6] opened 2023-08-24 15:25 UTC
FreeCAD 0.21.0 AppImage
Ubuntu 22.04.3 LTS

Opened a tool in the tool library editor and went to the Feeds and Speeds tab

```
18:21:45  Traceback (most recent call last):
18:21:45    File "/home/sgofferj/.local/share/FreeCAD/Mod/btl/./btl/ui/feedsandspeeds.py", line 40, in run
18:21:45      self.worker.start()
18:21:45    File "/home/sgofferj/.local/share/FreeCAD/Mod/btl/./btl/ui/feedsandspeeds.py", line 30, in start
18:21:45      self.result = self.fc.start(progress_cb=progress_cb)
18:21:45    File "/home/sgofferj/.local/share/FreeCAD/Mod/btl/./btl/feeds/calc.py", line 339, in start
18:21:45      results = self.calculate(progress_cb, iterations=iterations)
18:21:45    File "/home/sgofferj/.local/share/FreeCAD/Mod/btl/./btl/feeds/calc.py", line 320, in calculate
18:21:45      self.optimize()
18:21:45    File "/home/sgofferj/.local/share/FreeCAD/Mod/btl/./btl/feeds/calc.py", line 293, in optimize
18:21:45      result = minimize(self._evaluate_point,
18:21:45    File "/tmp/.mount_FreeCATUTG9K/usr/lib/python3.10/site-packages/scipy/optimize/_minimize.py", line 643, in minimize
18:21:45      bounds = _validate_bounds(bounds, x0, meth)
18:21:45    File "/tmp/.mount_FreeCATUTG9K/usr/lib/python3.10/site-packages/scipy/optimize/_minimize.py", line 996, in _validate_bounds
18:21:45      raise ValueError(msg)
18:21:45  ValueError: An upper bound is less than the corresponding lower bound.
18:21:46  Traceback (most recent call last):
18:21:46    File "/home/sgofferj/.local/share/FreeCAD/Mod/btl/./btl/ui/feedsandspeeds.py", line 40, in run
18:21:46      self.worker.start()
18:21:46    File "/home/sgofferj/.local/share/FreeCAD/Mod/btl/./btl/ui/feedsandspeeds.py", line 30, in start
18:21:46      self.result = self.fc.start(progress_cb=progress_cb)
18:21:46    File "/home/sgofferj/.local/share/FreeCAD/Mod/btl/./btl/feeds/calc.py", line 339, in start
18:21:46      results = self.calculate(progress_cb, iterations=iterations)
18:21:46    File "/home/sgofferj/.local/share/FreeCAD/Mod/btl/./btl/feeds/calc.py", line 320, in calculate
18:21:46      self.optimize()
18:21:46    File "/home/sgofferj/.local/share/FreeCAD/Mod/btl/./btl/feeds/calc.py", line 293, in optimize
18:21:46      result = minimize(self._evaluate_point,
18:21:46    File "/tmp/.mount_FreeCATUTG9K/usr/lib/python3.10/site-packages/scipy/optimize/_minimize.py", line 643, in minimize
18:21:46      bounds = _validate_bounds(bounds, x0, meth)
18:21:46    File "/tmp/.mount_FreeCATUTG9K/usr/lib/python3.10/site-packages/scipy/optimize/_minimize.py", line 996, in _validate_bounds
18:21:46      raise ValueError(msg)
18:21:46  ValueError: An upper bound is less than the corresponding lower bound.
18:21:46  Traceback (most recent call last):
18:21:46    File "/home/sgofferj/.local/share/FreeCAD/Mod/btl/./btl/ui/feedsandspeeds.py", line 40, in run
18:21:46      self.worker.start()
18:21:46    File "/home/sgofferj/.local/share/FreeCAD/Mod/btl/./btl/ui/feedsandspeeds.py", line 30, in start
18:21:46      self.result = self.fc.start(progress_cb=progress_cb)
18:21:46    File "/home/sgofferj/.local/share/FreeCAD/Mod/btl/./btl/feeds/calc.py", line 339, in start
18:21:46      results = self.calculate(progress_cb, iterations=iterations)
18:21:46    File "/home/sgofferj/.local/share/FreeCAD/Mod/btl/./btl/feeds/calc.py", line 320, in calculate
18:21:46      self.optimize()
18:21:46    File "/home/sgofferj/.local/share/FreeCAD/Mod/btl/./btl/feeds/calc.py", line 293, in optimize
18:21:46      result = minimize(self._evaluate_point,
18:21:46    File "/tmp/.mount_FreeCATUTG9K/usr/lib/python3.10/site-packages/scipy/optimize/_minimize.py", line 643, in minimize
18:21:46      bounds = _validate_bounds(bounds, x0, meth)
18:21:46    File "/tmp/.mount_FreeCATUTG9K/usr/lib/python3.10/site-packages/scipy/optimize/_minimize.py", line 996, in _validate_bounds
18:21:46      raise ValueError(msg)
18:21:46  ValueError: An upper bound is less than the corresponding lower bound.
18:21:46  Traceback (most recent call last):
18:21:46    File "/home/sgofferj/.local/share/FreeCAD/Mod/btl/./btl/ui/feedsandspeeds.py", line 40, in run
18:21:46      self.worker.start()
18:21:46    File "/home/sgofferj/.local/share/FreeCAD/Mod/btl/./btl/ui/feedsandspeeds.py", line 30, in start
18:21:46      self.result = self.fc.start(progress_cb=progress_cb)
18:21:46    File "/home/sgofferj/.local/share/FreeCAD/Mod/btl/./btl/feeds/calc.py", line 339, in start
18:21:46      results = self.calculate(progress_cb, iterations=iterations)
18:21:46    File "/home/sgofferj/.local/share/FreeCAD/Mod/btl/./btl/feeds/calc.py", line 320, in calculate
18:21:46      self.optimize()
18:21:46    File "/home/sgofferj/.local/share/FreeCAD/Mod/btl/./btl/feeds/calc.py", line 293, in optimize
18:21:46      result = minimize(self._evaluate_point,
18:21:46    File "/tmp/.mount_FreeCATUTG9K/usr/lib/python3.10/site-packages/scipy/optimize/_minimize.py", line 643, in minimize
18:21:46      bounds = _validate_bounds(bounds, x0, meth)
18:21:46    File "/tmp/.mount_FreeCATUTG9K/usr/lib/python3.10/site-packages/scipy/optimize/_minimize.py", line 996, in _validate_bounds
18:21:46      raise ValueError(msg)
18:21:46  ValueError: An upper bound is less than the corresponding lower bound.
```

**Comment by knipknap** [comment] 2023-08-24 15:36
The most likely cause is an invalid input parameter, like a zero height cutting edge or a stickout that is too small. Could you make a screenshot of the tool properties and the feeds&speeds tab?
Also it may help me to debug if you right click the results to show the hidden properties.

**Comment by knipknap** [comment] 2023-08-24 16:20
I just pushed an improvement already, with any luck the error message may now be better.

**Comment by sgofferj** [comment] 2023-08-24 18:24
![Screenshot_20230824_212103](https://github.com/knipknap/better-tool-library/assets/3258466/7b86d0ca-6439-460f-954c-68c6739b24ce)

![Screenshot_20230824_212153](https://github.com/knipknap/better-tool-library/assets/3258466/4534ba61-365e-4b5d-abde-edeb73f81667)

**Comment by knipknap** [comment] 2023-08-24 18:34
I think the problem is the chipload unit. I cannot reproduce your problem, and when using "0.025 mm" for the chipload it works for me.

I assume you haven't updated BTL since you last tried? Because otherwise you should at least see a better error message.

**Comment by knipknap** [comment] 2023-08-24 18:48
I pushed a fix for the micrometer unit issue. If you upgrade and try again the issue may be fixed.

**Comment by sgofferj** [comment] 2023-08-25 07:52
It seems to work now, yes. The error appeared to have occurred only with tools I added in 0.19. When I add a new tool in 0.21 through the plugin, everything works fine.

**Comment by sgofferj** [comment] 2023-08-25 07:59
WOW :fearful: 418mm/min at 7mm stepdown for a 1mm carbide splinter...

![Screenshot_20230825_105709](https://github.com/knipknap/better-tool-library/assets/3258466/9940c933-02e0-4136-b8ea-908740b7b75b)

![Screenshot_20230825_105721](https://github.com/knipknap/better-tool-library/assets/3258466/e1a78528-691b-46d2-bf03-2f25ff67ec31)

**Comment by knipknap** [comment] 2023-08-25 08:35
Hmmm, that doesn't seem entirely unreasonable to me given the small WOC with a dual flute carbide cutter in 6061? The radial force is certainly close to the limit, but the calculation assumes ideal conditions (i.e. perfect rigidity of the machine, zero runout). Hence the recommendation to start with half the given DOC.

What are good feeds&speeds in your experience with this cutter, and what type of machine are you using?

**Comment by sgofferj** [comment] 2023-08-25 09:39
I'm using a hobby-grade 3018 which I upgraded to MGN rails and a much better spindle. Certainly not perfect. But anything more than 0.1mm, MAYBE 0.2mm DOC, 0.25mm WOC, 300mm/m and the cutter breaks. That's a pretty good difference.

**Comment by sgofferj** [comment] 2023-08-25 09:41
In any case, the original issue seems to be fixed, so feel free to close this! And thank you for your work! It helps me a lot in my hobby!

**Comment by knipknap** [comment] 2023-08-25 10:05
Ahh, I see. That's how I started as well, but luckily was able to upgrade to a much better machine.

Yeah, no chance these parameters could possibly work in that case - most likely your spindle runout is the limiting factor. I may add some additional parameters to the machine dialog in the future, to allow for taking machine rigidity and runout into account.

Thanks for the bug report.

**Closed by knipknap** 2023-08-25 10:05 UTC
